# Carregar pacotes
library(flexdashboard)
library(readr)
library(highcharter)
library(shinyWidgets)
library(rbcb)
library(ggplot2)
library(rdbnomics)
library(dplyr)
library(magrittr)
library(stringr)
library(countrycode)
library(tidyr)
library(DBI)
library(duckdb)
library(lubridate)