on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * *'

name: Publicação de Aplicações

jobs:
  Deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar esse repositório
        uses: actions/checkout@v3

      - name: Instalar o R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
          use-public-rspm: true

      - name: Instalar apcotes de R
        uses: r-lib/actions/setup-renv@v2
      
      - name: Extração, Transfomação, Disponibilização
        run: |
          source("./R/00_pacotes.R")
          source("./R/01_funcoes.R")
          source("./R/02_extacao.R")
          source("./R/03_transformacao.R")
          source("./R/04_disponibilizacao.R")
       shell: Rscript {0}

      - name: Instalar o  Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderizar o relatóio no Quarto 
        run: |
          cp -r report/* ./
          quarto render Aplicacao/relatorio.qmd
          
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Atualização de aplicações